OBJ = gcc -Wall -c  

all: step1 step2 step3 step4 step5 step6 step7 step8

clean:
	rm -f step1 step2 step3 step4 step5 step6 step7 step8 *.o

step1: step1.o
	gcc step1.o -o step1

step1.o: step1.c
	${OBJ} step1.c

step2: step2.o
	gcc step2.o -o step2

step2.o: step2.c
	${OBJ} step2.c

step3: step3.o
	gcc step3.o -o step3

step3.o: step3.c
	${OBJ} step3.c

step4: step4.o
	gcc step4.o -o step4

step4.o: step4.c
	${OBJ} step4.c

step5: step5.o
	gcc step5.o -o step5

step5.o: step5.c
	${OBJ} step5.c

step6: step6.o
	gcc step6.o -o step6

step6.o: step6.c
	${OBJ} step6.c

step7: step7.o
	gcc step7.o -o step7

step7.o: step7.c
	${OBJ} step7.c

step8: step8.o
	gcc step8.o -o step8

step8.o: step8.c
	${OBJ} step8.c
